version: '3.8'

# Example usage of the kicker5000 image
services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    env_file:
      - .env
    environment:
      - RCON=TRUE
      - RCON_PASSWORD=password
    volumes:
      - ./mc-data:/data
  kicker5000:
    image: kicker5000
    depends_on:
      mc:
        condition: service_healthy
    environment:
      - RCON_HOST=mc
      - RCON_PORT=25575
      - RCON_PASSWORD=password 